- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages to latest
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
    state: latest
