---
- name: Ensure docker directories exist
  file:
    path: "{{ hb_volume_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - portainer/data
    - homarr/configs
    - homarr/icons
    - homarr/data
    - bitwarden

- name: Ensure support directory exist
  file:
    path: "{{ docker_services_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - support

- name: Deploy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_services_dir }}/support/docker-compose.yml"
    mode: '0644'

- name: Start support services
  command: docker compose up -d
  args:
    chdir: "{{ docker_services_dir }}/support"